#!/bin/bash
set -e

# WORKAROUND:  Public traffic to 80 and 443 will be DNAT-ed by Docker
#              iptable rules. Traffik from containers targeting the
#              host will not be processed by said NAT rules (a bug in the
#              iptable rules generated by Docker?).
#              Luckily Docker still executes userland proxys for published
#              ports. Therefore we can ACCEPT traffik to 80 and 443 as a
#              workaround.
# TO BE CLEAR: These ACCEPT rules do not affect traffik originating from
#              the internet!
append-rule 4,6 filter INPUT -p tcp -m tcp --dport 80 -j ACCEPT
append-rule 4,6 filter INPUT -p tcp -m tcp --dport 443 -j ACCEPT
