- name: 'project deploy : deploy service container : {{ service }}'
  docker_container:
    name:            '{{ project | project_get_service_name(service) }}'
    image:           '{{ project | project_get_service_image(service) }}'
    env:             '{{ project | project_get_service_env(service) }}'
    labels:          '{{ project | project_get_service_labels(service) }}'
    volumes:         '{{ project | project_get_service_volumes(service) }}'
    networks:        '{{ project | project_get_service_networks(service) }}'
    command:         '{{ project | project_get_service_command(service) }}'
    purge_networks:  true
    exposed_ports:   '{{ project | project_get_service_exposed_ports(service) }}'
    published_ports: '{{ project | project_get_service_published_ports(service) }}'
    capabilities:    '{{ project | project_get_service_capabilities(service) }}'
    restart_policy:  'unless-stopped'
    state:           '{{ project | project_get_service_state(service) }}'
    log_driver:      'json-file'
    log_options:
      max-size: '10m'
  async: 3600
  poll: 0
  register: deploy_wait

- name: 'project deploy : deploy service container : {{ service }} : wait'
  async_status:
    jid: '{{ deploy_wait.ansible_job_id }}'
  register: deploy_result
  until: deploy_result.finished
  retries: 360
  delay: 10
